### ISSUE TITLE
Isn't Astro build process supposed to take care of this?

### ISSUE THREAD

**Issue by kaushalyap** [sondr3/astro-compressor#1]
Why need a separate plugin?

**Comment by sondr3** [comment]
I doubt it, neither Gatsby, NextJS nor Astro does any ahead-of-time compression of resources because it can be a pitfall of problems if users aren't aware of if happening. If you deploy to any of the popular hosting-as-a-service providers (Vercel, Netlify, etc) they do this dynamically for you and so pre-compressed resources may interact weirdly with them. If you host it yourself, as I do, you can either dynamically (de)compress them via your webserver (Caddy, Nginx, Apache) or compress them ahead of time to reduce CPU cycles.

Hope that clears it up 🙂
